services:

  app:
    container_name: song_library
    build: .
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "8090:8090"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - my_network
   

  postgres:
    container_name: song_library_pgdb
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - my_network

volumes:
  pg-data:
networks:
  my_network:
    driver: bridge